version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    container_name: 'prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana
    container_name: 'grafana'
    ports:
      - '3000:3000'
    depends_on:
      - prometheus