global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'apps-monitoring'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['EXTERNAL_IP:8081']
        labels:
          application: 'FirstApp'
      - targets: ['EXTERNAL_IP:8082']
        labels:
          application: 'SecondApp'